### ISSUE TITLE
Responsive YouTube Loading Issues

### ISSUE THREAD

**Issue by FrugalGeek** [Sommerregen/grav-plugin-mediaembed#3]
The preview image that appears seems slightly skewed on responsive settings. Once you click the giant play button it looks fine, but even with preview turned off it loads this skewed pane.

![78d56ac6-f009-11e4-96af-7183497cc70f](https://cloud.githubusercontent.com/assets/4026828/7476928/57221e00-f316-11e4-96a8-4eda365868d6.png)

![77f3b612-f009-11e4-852c-8512ba17d710](https://cloud.githubusercontent.com/assets/4026828/7476927/57217306-f316-11e4-9d37-dbdc1c94a9ff.png)

**Comment by Sommerregen** [comment]
Hi FrugalGeek,

I'm aware of the issue. Actually this is a `responsive: true` issue. It will happen, when the mediaembed container is bigger than the media size (`media.width`/`media.height`). Sometimes this also happens when the iframe contains a width or height attribute. Since the media are embedded slight differently at the moment (because of different media types), I don't know how to solve it.

I need to parse at least the `oembed.html` attribute and modify there the iframes. The only workaround for now I can imagine is to set `responsive: false` and set a big width/height in `media` settings. Although responsive is switched off, the media will nevertheless shrink to the surrounding container size.
