### ISSUE TITLE
Overlay play button not working

### ISSUE THREAD

**Issue by bdillahu** [Sommerregen/grav-plugin-mediaembed#5]
When I have a youtube video (haven't tried others) - when I'm running on local php in development, all looks good - big white "play" button over the thumbnail of the video.

When I move it to my hosting provider (Dreamhost), the overlay doesn't work. The play button and the "circle" (I assume) appear below the video, and the layout is off.

I tried responsive both ways, but it doesn't change that.

Any ideas?

**Comment by Sommerregen** [comment]
Mh, unfortunately not. I know the play button can somehow cause problems (not right aligned depending on the browser you use), but yours is different. Can you explain by what yu meaning "the layout is off"? Can you at least see the preview image? If not maybe you have different config files (`user/plugins/mediaembed.yaml` or `user/config/plugins/mediaembed.yaml`). You can further check, whether the video is visible (and controllable) by switching off temporarily the `preview` option. Then, the video is directly embedded without the play button and the video is loaded once you called the page.

Otherwise can you point me to your hosted version? It is always the best to see it in an environment, which causes troubles.

**Comment by bdillahu** [comment]
As a start, so you can see what I’m talking about:

http://www.craftacraft.com/home/2014-11-28-ranger_tug_r-25 <http://www.craftacraft.com/home/2014-11-28-ranger_tug_r-25>

You’ll note the play button at the bottom.

Clicking the button toggles the checkbox (not sure what that’s all about). The thumbnail appears, and if you click on the image it takes you to Youtube and plays it (but not in my site).

I do have externallinks plugin enabled, but in my testing things weren’t different without it.



-- 
Bruce C. Dillahunty
http://www.emptyworlds.com

**Comment by bdillahu** [comment]
Oh, sorry, about the layout being off… the vertical space between the bottom of the image and the navigation buttons changes…

The example:

http://www.craftacraft.com/home/2014-11-28-ranger_tug_r-25 <http://www.craftacraft.com/home/2014-11-28-ranger_tug_r-25>

Is too big… normally, looks like this:

http://www.craftacraft.com/blogs/origami_dinghy/flapdoodle_another_folding_dinghy_design

-- 
Bruce C. Dillahunty
http://www.emptyworlds.com

**Comment by Sommerregen** [comment]
Hi @bdillahu,

I was looking at your site. Your issue comes from the fact, that the corresponding stylesheet and javascript of the **MediaEmbed** plugin isn't loaded. And since without any stylesheet it will fall down to the layout you see.

Thus, I suspect that either [`built_in_css`](https://github.com/Sommerregen/grav-plugin-mediaembed/blob/master/mediaembed.yaml#L4) or [`built_in_js`](https://github.com/Sommerregen/grav-plugin-mediaembed/blob/master/mediaembed.yaml#L5) is set to false or more likely that your cache is stale. The latter you can check by deleting all contents in Grav's `cache` folder manually or by using the [**CacheBuster plugin**](https://github.com/Gertt/grav-plugin-cachebuster). I hope this will solve the problem. If not maybe something goes wrong with the pipelining of CSS and/or JavaScript. It is worth to temporarily switch it off, too, clear the cache and see whether it solves the problem or not. Since you modified Antimatter a bit, it could be that something goes wrong, too.

Please tell me whether none of the above ideas work. Then, I must have a deeper look. It would be good, if you could zip me then your grav install only with that page and template (the others you can delete) and send it to me e.g. via email sommerregen@benjamin-regler.de or post the link here.

**Comment by bdillahu** [comment]
Following your leads, I tried falling back to default antimatter... that
didn't change anything.

Cleared cache (command line and manually) - no change.

You mentioned CSS/Javascript "missing" - decided a re-install couldn't
hurt, so ran:

bin/gpm install mediaembed

It asked to overwrite and I said "yes". 

Now it all works!

I can only surmise it got a corrupted load somehow, or I managed to
accidentally remove something I wasn't seeing (most probably).

Thanks so much for the time and help on this! (and of course for your work
on a great pluging!)

Bruce

**Comment by Sommerregen** [comment]
Dear Bruce,

glad to hear that all is sorted now and that you solved your problem by simply re-installing the plugin (good thought :+1:).

If you need more help or have questions, then please don't hesitate to ask :-)

Wish you all the best,
Benny
